FROM ubuntu:xenial

RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
     && apt-get clean \
     && apt-get update --fix-missing

RUN \
    DEBIAN_FRONTEND=noninteractive \
    apt-get upgrade -y \
    && apt-get install --fix-missing -y \
            make \
            git \
            locales \
            supervisor \

    && git clone --branch=0.8 --depth=1 https://github.com/unoconv/unoconv.git \
    && make install -C unoconv \
    && apt-get -q -y remove git libreoffice-gnome make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN locale-gen de_DE.UTF-8
ENV LANG=de_DE.UTF-8 \
    LANGUAGE=de_DE:de \
    LC_ALL=de_DE.UTF-8

COPY gouno /go/bin/gouno
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY boot.sh ./
RUN chmod 777 boot.sh

EXPOSE 3000

ENTRYPOINT ["./boot.sh"]
